FROM golang:bullseye AS builder

ENV LANG=C.UTF-8
ENV TZ=Asia/Shanghai

ENV CGO_ENABLED=0
ENV GOPROXY=https://goproxy.cn,direct

#set timezone 
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8


# change apt source 
RUN sed -i 's/\w*.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list


