FROM golang:alpine AS builder

ENV LANG=C.UTF-8
ENV TZ=Asia/Shanghai

ENV CGO_ENABLED=0
ENV GOPROXY=https://goproxy.cn,direct

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk update --no-cache && apk add --no-cache ca-certificates tzdata gcc make


