FROM alpine:3.17

LABEL mantainer="serialt <tserialt@gmail.com> build a vm image"

#set timezone 
ENV LANG=C.UTF-8
ENV TZ=Asia/Shanghai


RUN apk update --no-cache && apk add --no-cache ca-certificates tzdata

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
