version: "3"

networks:
  gitea:
    external: false

services:
  drone-server:
    image: drone/drone:2.11.1
    container_name: drone-server
    hostname: drone-server
    restart: always
    environment:
      DRONE_GITEA_SERVER: https://local.com
      DRONE_GITEA_CLIENT_ID: "86e0b83e-xxxxxxxxxxxxxxxxxxxxxxxxx"
      DRONE_GITEA_CLIENT_SECRET: "ITWTl7O28mxxxxxxxxxxxxxxxxxxxxxxxxxx"
      DRONE_RPC_SECRET: "0ceea14c2ef9760ab07309bd3ed5c3c2"
      DRONE_SERVER_HOST: drone.local.com
      DRONE_SERVER_PROTO: https
      DRONE_USER_CREATE: username:serialt,admin:true
    ports:
      - "127.0.0.1:5001:80"
    volumes:
      - "/data/drone:/var/lib/drone"
      - "/data/drone-data:/data"
    networks:
      - gitea

  drone-runner:
    image: drone/drone-runner-docker:1.8.0
    container_name: drone-runner-docker
    hostname: drone-runner-docker
    restart: always
    depends_on:
      - drone-server
    environment:
      DRONE_RPC_PROTO: https
      DRONE_RPC_HOST: drone.local.com
      DRONE_RPC_SECRET: 0ceexxxxxxxxxxxxxxxxxxxxxxxxx
      DRONE_RUNNER_CAPACITY: 5
      DRONE_RUNNER_NAME: serialt-runner
    ports:
      - "127.0.0.1:5002:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
    networks:
      - gitea        
