version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    privileged: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}/ssl:/etc/nginx/cert_files"
      - "${PWD}/conf.d:/etc/nginx/conf.d"
      - "/data/nginx/log:/var/log/nginx"
      - "/data/www.local.com:/data/www.local.com"
    network_mode: "host"
