ARG FROM=node:16-alpine3.16
FROM ${FROM}
ENV LANG=C.UTF-8
ENV TZ=Asia/Shanghai

LABEL mantainer="serialt <tserialt@gmail.com> alpine image"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk add --update --no-cache coreutils && \
    apk add --no-cache curl

RUN addgroup -S build && adduser -S build -G build
USER build
WORKDIR /build

RUN npm install pm2  -y --registry=https://registry.npmmirror.com
