version: "3"
services:
  db:
    restart: always
    container_name: mysql
    image: "mysql:5"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "centos"
      MYSQL_DATABASE: "imau"
      MYSQL_USER: "imau"
      MYSQL_PASSWORD: "centos"
    command: |
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/conf:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime:ro
